require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LiftsetsController do

  # This should return the minimal set of attributes required to create a valid
  # Liftset. As you add validations to Liftset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "setnum" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LiftsetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all liftsets as @liftsets" do
      liftset = Liftset.create! valid_attributes
      get :index, {}, valid_session
      assigns(:liftsets).should eq([liftset])
    end
  end

  describe "GET show" do
    it "assigns the requested liftset as @liftset" do
      liftset = Liftset.create! valid_attributes
      get :show, {:id => liftset.to_param}, valid_session
      assigns(:liftset).should eq(liftset)
    end
  end

  describe "GET new" do
    it "assigns a new liftset as @liftset" do
      get :new, {}, valid_session
      assigns(:liftset).should be_a_new(Liftset)
    end
  end

  describe "GET edit" do
    it "assigns the requested liftset as @liftset" do
      liftset = Liftset.create! valid_attributes
      get :edit, {:id => liftset.to_param}, valid_session
      assigns(:liftset).should eq(liftset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Liftset" do
        expect {
          post :create, {:liftset => valid_attributes}, valid_session
        }.to change(Liftset, :count).by(1)
      end

      it "assigns a newly created liftset as @liftset" do
        post :create, {:liftset => valid_attributes}, valid_session
        assigns(:liftset).should be_a(Liftset)
        assigns(:liftset).should be_persisted
      end

      it "redirects to the created liftset" do
        post :create, {:liftset => valid_attributes}, valid_session
        response.should redirect_to(Liftset.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved liftset as @liftset" do
        # Trigger the behavior that occurs when invalid params are submitted
        Liftset.any_instance.stub(:save).and_return(false)
        post :create, {:liftset => { "setnum" => "invalid value" }}, valid_session
        assigns(:liftset).should be_a_new(Liftset)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Liftset.any_instance.stub(:save).and_return(false)
        post :create, {:liftset => { "setnum" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested liftset" do
        liftset = Liftset.create! valid_attributes
        # Assuming there are no other liftsets in the database, this
        # specifies that the Liftset created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Liftset.any_instance.should_receive(:update).with({ "setnum" => "1" })
        put :update, {:id => liftset.to_param, :liftset => { "setnum" => "1" }}, valid_session
      end

      it "assigns the requested liftset as @liftset" do
        liftset = Liftset.create! valid_attributes
        put :update, {:id => liftset.to_param, :liftset => valid_attributes}, valid_session
        assigns(:liftset).should eq(liftset)
      end

      it "redirects to the liftset" do
        liftset = Liftset.create! valid_attributes
        put :update, {:id => liftset.to_param, :liftset => valid_attributes}, valid_session
        response.should redirect_to(liftset)
      end
    end

    describe "with invalid params" do
      it "assigns the liftset as @liftset" do
        liftset = Liftset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Liftset.any_instance.stub(:save).and_return(false)
        put :update, {:id => liftset.to_param, :liftset => { "setnum" => "invalid value" }}, valid_session
        assigns(:liftset).should eq(liftset)
      end

      it "re-renders the 'edit' template" do
        liftset = Liftset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Liftset.any_instance.stub(:save).and_return(false)
        put :update, {:id => liftset.to_param, :liftset => { "setnum" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested liftset" do
      liftset = Liftset.create! valid_attributes
      expect {
        delete :destroy, {:id => liftset.to_param}, valid_session
      }.to change(Liftset, :count).by(-1)
    end

    it "redirects to the liftsets list" do
      liftset = Liftset.create! valid_attributes
      delete :destroy, {:id => liftset.to_param}, valid_session
      response.should redirect_to(liftsets_url)
    end
  end

end
